apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-apikey
  labels:
    {{- include "etherpad.labels" . | nindent 4 }}
type: Opaque
data:
  APIKEY.txt: {{  .Values.etherpad.API_KEY | b64enc | quote }}